# Generated by Django 4.0.5 on 2022-07-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_familia_delete_curso_delete_entregable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='apellido2',
            field=models.CharField(default='String', max_length=30),
        ),
        migrations.AddField(
            model_name='familia',
            name='apellido3',
            field=models.CharField(default='String2', max_length=30),
        ),
        migrations.AddField(
            model_name='familia',
            name='edad2',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='familia',
            name='edad3',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='familia',
            name='fechaDeNacimiento2',
            field=models.DateField(default='2222-12-22'),
        ),
        migrations.AddField(
            model_name='familia',
            name='fechaDeNacimiento3',
            field=models.DateField(default='2222-12-22'),
        ),
        migrations.AddField(
            model_name='familia',
            name='nombre2',
            field=models.CharField(default='aaa', max_length=30),
        ),
        migrations.AddField(
            model_name='familia',
            name='nombre3',
            field=models.CharField(default='aaa', max_length=30),
        ),
        migrations.AlterField(
            model_name='familia',
            name='fechaDeNacimiento',
            field=models.DateField(default='2222-12-22'),
        ),
    ]
