# Generated by Django 4.0.5 on 2022-07-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_alter_familia_fechadenacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='fechaDeNacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='familia',
            name='fechaDeNacimiento2',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='familia',
            name='fechaDeNacimiento3',
            field=models.DateField(),
        ),
    ]
